blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('comment/<int:pk>/approve/',
         views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post,
         name='add_comment_to_post'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('', views.post_list, name='post_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', include('blog.urls')),
]

blog/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='автор'
    )
    title = models.CharField(
        max_length=200,
        verbose_name='заголовок'
    )
    text = models.TextField(
        verbose_name='текст'
    )
    created_date = models.DateTimeField(
        default=timezone.now,
        verbose_name='дата создания'
    )
    published_date = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name='дата публикации'
    )

    def publish(self) -> None:
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        'blog.Post',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.CharField(
        max_length=200,
        verbose_name='автор'
    )
    text = models.TextField(
        verbose_name='комментарий'
    )
    created_date = models.DateTimeField(
        default=timezone.now(),
        verbose_name='дата создания'
    )
    approved_comment = models.BooleanField(
        default=False
    )

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

blog/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = (
            'title',
            'text',
        )


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = (
            'text',
        )

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .models import Post, Comment
from .forms import PostForm, CommentForm


def post_list(request):
    posts = Post.objects.filter(
        published_date__lte=timezone.now()
    ).order_by(
        '-published_date'
    )
    return render(
        request,
        'blog/post_list.html',
        context={
            'posts': posts
        }
    )


def post_detail(request, pk):
    post = get_object_or_404(
        Post,
        pk=pk
    )
    return render(
        request,
        'blog/post_detail.html',
        {'post': post}
    )


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(
        request,
        'blog/post_edit.html',
        {'form': form}
    )


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(
                'blog:post_detail',
                pk=post.pk
            )
    else:
        form = PostForm(instance=post)
    return render(
        request,
        'blog/post_edit.html',
        {'form': form}
    )


@login_required
def post_draft_list(request):
    posts = Post.objects.filter(
        published_date__isnull=True
    ).order_by(
        'created_date'
    )

    return render(
        request,
        'blog/post_draft_list.html',
        {'posts': posts}
    )


@login_required
def post_publish(requset, pk):
    post = get_object_or_404(
        Post,
        pk=pk
    )
    post.publish()
    return redirect(
        'blog:post_list',
        pk=pk
    )


@login_required
def post_remove(request, pk):
    post = get_object_or_404(
        Post,
        pk=pk
    )
    post.delete()
    return redirect(
        "blog:post_list"
    )


def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)

blog/templates/blog/add_comment_to_post.html
{% extends "base.html" %}

{% block content %}
    <h1>Новый комментарий</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Отправить</button>
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>{{ post.title }}</title>
{% endblock %}


{% block content %}
    <div class="post">
      {% if post.published_date %}
        <div class="date">
          {{ post.published_date }}
          <p> Автор публикации: {{ post.author }} </p>
        </div>
      {% else %}
        <a class="btn btn-default" 
          href="{% url 'blog:post_publish' pk=post.pk %}">Опубликовать
        </a>
      {% endif %}
        {% if user.is_authenticated %}
          <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>
          <a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}">
            <span class="glyphicon glyphicon-remove"></span>
          </a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
    <hr>
    <a class="btn btn-default" 
      href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Добавить комментарий
    </a>
    {% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
    <div class="comment">
        <div class="date">
            {{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"> Удалить
                </a>
                <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"> Опубликовать
                </a>
            {% endif %}
        </div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
    {% endif %}
{% empty %}
      <p>Комментариев пока нет :(</p>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'base.html' %}


{% block title %}
  <title>Неопубликованные посты</title>
{% endblock %}

{% block content %}
  {% for post in posts %}
      <div class="post">
        <p class="date">Создан: {{ post.created_date|date:'d-m-Y' }}</p>
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <p>{{ post.text|truncatechars:200 }}</p>
      </div>
  {% endfor %}
  
{% endblock %}

blog/templates/blog/post_edit.html
{% extends "base.html" %}

{% block content %}
  <h1>Новый пост</h1>
    <form method="POST" class="post-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="save btn btn-default">Сохранить</button>
      
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Django blog</title>
{% endblock %}

{% block content %}

              {% for post in posts %}
                  <hr>
                  <div class="post">
                      
                      <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">
                        {{ post.title }}</a></h2>
                      <p>{{ post.text|linebreaksbr }}</p>
                  </div>
                  <div class="date">
                    <p>Автор публикации: {{ post.author }} Опубликовано: {{ post.published_date }}</p>
                  </div>
                  <a href="{% url 'blog:post_detail' pk=post.pk %}">Комментарии: 
                    {{ post.approved_comments.count }}
                  </a>
              {% endfor %}

{% endblock %}

templates/base.html
{% load static %}
<html>
  <head>
    
    <link rel="stylesheet" 
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" 
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" 
      type="text/css">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    {% block title %}
    {% endblock %}
  </head>
  <body>
    <div class="page-header">
      
      {% include "includes/header.html" %}
    </div>
    <main>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
              {% block content %}
              {% endblock %}
            </div>
        </div>
    </div>
  </main>
    <div>
      {% include "includes/footer.html" %}
    </div>
  </body>
</html>

templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© Блог</p>    
</footer>

templates/includes/header.html
{% load static %}

{% if user.is_authenticated %}
  <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
  <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
  <p class="top-menu">Привет {{ user.username }} <small>(<a href="{% url 'logout' %}">Выйти</a>)</small></p>
{% else %}
        
  <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
{% endif %}
<header>
  <h1><a href="{% url 'blog:post_list' %}">Django Blog</a></h1>
</header>